packages:
  - package
  - examples/*
  - docs/wiki

catalogs:
  typedoc:
    browser-sync: ^3.0.4
    typedoc: ^0.28.18
  wiki:
    "@astrojs/starlight": ^0.38.3
    astro: ^6.0.1
    sharp: ^0.34.2

onlyBuiltDependencies:
  - esbuild
  - sharp

