name: docs

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Install Dependencies
        run: nix develop --command bash -c "pnpm install"
      - name: Generate Type Definitions
        run: nix develop --command bash -c "pnpm run ags:types"
      - name: Build Typedoc (tadaima)
        run: nix develop --command bash -c "pnpm run tadaima:typedoc:build"
      - name: Build Typedoc (tadaima-cli)
        run: nix develop --command bash -c "pnpm run tadaima-cli:typedoc:build"
      - name: Assemble Publish Directory
        run: |
          mkdir -p _site
          cp -r docs/ _site
          cp -r packages/tadaima/docs _site/tadaima
          cp -r packages/tadaima-cli/docs _site/tadaima-cli
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
