name: docs

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Install dependencies
        run: nix develop --command bash -c "pnpm install"
      - name: Generate type definitions
        run: nix develop --command bash -c "pnpm run ags:types"
      - name: Build Typedoc (tadaima)
        run: nix develop --command bash -c "pnpm run tadaima:typedoc:build"
      - name: Build Typedoc (tadaima-cli)
        run: nix develop --command bash -c "pnpm run tadaima-cli:typedoc:build"
      - name: Build Vitest UI (@vitest/ui for tadaima-cli)
        id: vitest
        continue-on-error: true
        run: nix develop --command bash -c "pnpm run tadaima-cli:test:ui"
      - name: Build Vitest Coverage (@vitest/coverage-v8 for tadaima-cli)
        continue-on-error: true
        run: nix develop --command bash -c "pnpm run tadaima-cli:test:coverage"
      - name: Assemble Publish Directory
        run: |
          mkdir -p _site
          cp -r docs/api _site/tadaima/typedoc
          cp -r docs/api-cli _site/tadaima-cli/typedoc
          cp -r packages/tadaima-cli/html _site/tadaima-cli/test/ui || true
          cp -r packages/tadaima-cli/coverage _site/tadaima-cli/test/coverage || true
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
      - name: If Failed Test, exit 1
        if: steps.vitest.outcome == 'failure'
        run: exit 1

